python px4_mavros_run_uav1.py&
python px4_mavros_run_uav2.py&
python px4_mavros_run_uav3.py&
python px4_mavros_run_uav4.py&
sleep 10s
python commander_uav1.py&
python commander_uav2.py&
python commander_uav3.py&
python commander_uav4.py&
