std_msgs/Header header

bool fc_connected
int32 flight_mode
bool armed

float64 battery_soc_percentage


float64 temperature_celsius
float64 imu_ax
float64 imu_ay
float64 imu_az
float64 imu_wx
float64 imu_wy
float64 imu_wz
float64 imu_filtered_qx
float64 imu_filtered_qy
float64 imu_filtered_qz
float64 imu_filtered_qw


int32 guide_mode

int32 gps_avail_satellite_count

int32 gps_fix_status
float64 gps_longitude
float64 gps_latitude
float64 gps_altitude
float64 gps_lon_dop
float64 gps_lat_dop
float64 gps_alt_dop

float64 vehicle_vx
float64 vehicle_vy
float64 vehicle_vz

std_msgs/String optinal_values_json
